export const ACTIVE_COMPONENTS = " ACTIVE_COMPONENTS";
export const ACTIVE_CONVERSATIONS = " ACTIVE_CONVERSATIONS";
export const ACTIVE_FRIENDS = " ACTIVE_FRIENDS";
export const ACTIVE_CALL = "ACTIVE_CALL";
